# Generated by Django 4.0.4 on 2022-07-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anecdots', '0002_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anecdot',
            name='title',
        ),
        migrations.AlterField(
            model_name='authors',
            name='author_name',
            field=models.CharField(max_length=100),
        ),
    ]
