# Generated by Django 4.0.4 on 2022-07-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anecdots', '0003_remove_anecdot_title_alter_authors_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='anecdot',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anecdots.authors'),
            preserve_default=False,
        ),
    ]
