# Generated by Django 4.0.4 on 2022-07-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anecdots', '0004_anecdot_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anecdot',
            name='author',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
