# Generated by Django 4.0.5 on 2022-07-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anecdots', '0008_anecdot_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
